services:
  bh-monitor:
    image: bh-monitor
    build:
      context: .
      dockerfile: ServerMonitor/Dockerfile
    environment:
      SERVER_URL: "${EXPORT_PORT}"
      PING_TARGET: "${PING_TARGET}"
      CHECK_INTERVAL: "${CHECK_INTERVAL}"
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
    restart: unless-stopped
    
