#!/bin/bash

# Extract the service name
SERVICE_NAME="$1"
# Default value for the flag
HARD_FLAG=false

# Loop through arguments to check for --hard
for arg in "$@"; do
    if [[ "$arg" == "--hard" ]]; then
        HARD_FLAG=true
        break
    fi
done


. "./Scripts/Services/$SERVICE_NAME"

echo "Running docker compose $COMPOSE_TARGETS down"
docker compose $COMPOSE_TARGETS down

if $HARD_FLAG; then
  docker rmi $TARGET_IMAGE
fi

if [ ! -f ".env" ]; then
  echo ".env file not found! Exiting..."
  exit 1
fi

echo "Running docker compose $COMPOSE_TARGETS up -d"
docker compose $COMPOSE_TARGETS up -d