#!/bin/bash

if [ ! -f ".env" ]; then
  cp ./.env.template .env
  echo ".env file not found and copied from .env.template! Configure it before start!"
  exit 1
fi

# Extract the service name
SERVICE_NAME="$1"
. "./Scripts/Services/$SERVICE_NAME"

echo "Running docker compose $COMPOSE_TARGETS up -d"
docker compose $COMPOSE_TARGETS up -d