#!/bin/bash

# Extract the service name
SERVICE_NAME="$1"
. "./Scripts/Services/$SERVICE_NAME"

"docker compose" "$COMPOSE_TARGETS" "down"

git fetch
git pull

if [ ! -f ".env" ]; then
  echo ".env file not found! Exiting..."
  exit 1
fi

"docker compose" "$COMPOSE_TARGETS" "up -d" 