#!/bin/bash

# Extract the service name
SERVICE_NAME="$1"
. "./Scripts/Services/$SERVICE_NAME"

echo "Running docker compose $COMPOSE_TARGETS down"
docker compose "$COMPOSE_TARGETS" down
docker rmi $TARGET_IMAGE

git fetch
git pull

if [ ! -f ".env" ]; then
  echo ".env file not found! Exiting..."
  exit 1
fi

echo "Running docker compose $COMPOSE_TARGETS up -d"
docker compose $COMPOSE_TARGETS up -d